### ISSUE TITLE
After migrating to 8.0.0.beta: Cannot Access MacAlgorithm

### ISSUE THREAD

**Issue by dave0688** [jhipster/generator-jhipster#22556]
##### **Overview of the issue**

After upgrading to jHipster 8.0.0 I'm running into the following compilation error:

```
src/test/java/com/myApp/app/security/jwt/JwtAuthenticationTestUtils.java:55:46
java: cannot access MacAlgorithm
  class file for MacAlgorithm not found
```

I'm on a macbook, if that helps.

Also I tried to debug, but this `MacAlgorithm` comes from spring itself, so not sure why it cannot access it.

I also opened a stackoverflow issue:
https://stackoverflow.com/questions/76471526/java-spring-boot-cannot-access-macalgorithm

##### **Motivation for or Use Case**

I want to project to compile.

##### **Reproduce the error**

Execute `./mvnw`

##### **JHipster Version(s)**

8.0.0.beta

##### **Browsers and Operating System**

MacOS Ventura 13.4
Chrome

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can you provide the output of `jhipster info` so we can try to reproduce this issue? 

It might be that Maven didn't download the artifacts correctly. You can remove your local Maven repo and try again. 

```
rm -rf ~/.m2/repository
```

**Comment by dave0688** [comment]
Thank you very much for your answer. 
For some reason the issue is gone. It might really have been a cache issue. After cleaning the project, deleting the target folder and rebuilding I don't have it anymore.

Thanks for your help, and I would let you know if it happens again.
