### ISSUE TITLE
Jhispter 6.7.0 issues: missing javax.servlet-api and Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean

### ISSUE THREAD

**Issue by fredericBregier** [jhipster/generator-jhipster#11281]
##### **Overview of the issue**
I was using old version 6.6.0. After upgrading to 6.7.0 I cannot anymore build my project.
Therefore I started a new one from scratch, using all default values.

    jhipster

Then, when running

    ./mvnw  -Pwebpack 

I've got a first error, simple to correct:

    [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ waarp-test ---
    [INFO] Changes detected - recompiling the module!
    [INFO] Compiling 70 source files to /home/frederic/eclipse/vaadin/workspace/WaarpTest/target/classes
    [INFO] -------------------------------------------------------------
    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[19,8] cannot access javax.servlet.Filter class file for javax.servlet.Filter not found
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/config/WebConfigurer.java:[21,1] package javax.servlet does not exist
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[8,21] package javax.servlet does not exist
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[9,21] package javax.servlet does not exist
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[10,21] package javax.servlet does not exist
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[11,21] package javax.servlet does not exist
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[12,26] package javax.servlet.http does not exist
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[30,26] cannot find symbol
      symbol:   class ServletRequest
      location: class org.waarp.share.security.jwt.JWTFilter
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[30,57] cannot find symbol
      symbol:   class ServletResponse
      location: class org.waarp.share.security.jwt.JWTFilter
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[30,90] cannot find symbol
      symbol:   class FilterChain
      location: class org.waarp.share.security.jwt.JWTFilter
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[31,29] cannot find symbol
      symbol:   class ServletException
      location: class org.waarp.share.security.jwt.JWTFilter
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/security/jwt/JWTFilter.java:[41,33] cannot find symbol
      symbol:   class HttpServletRequest
      location: class org.waarp.share.security.jwt.JWTFilter
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/web/rest/AccountResource.java:[91,35] cannot find symbol
      symbol:   class HttpServletRequest
      location: class org.waarp.share.web.rest.AccountResource
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/config/WebConfigurer.java:[48,27] cannot find symbol
      symbol:   class ServletContext
      location: class org.waarp.share.config.WebConfigurer
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/config/WebConfigurer.java:[48,65] cannot find symbol
      symbol:   class ServletException
      location: class org.waarp.share.config.WebConfigurer
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/config/WebConfigurer.java:[119,47] cannot find symbol
      symbol:   class ServletContext
      location: class org.waarp.share.config.WebConfigurer
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/config/WebConfigurer.java:[120,55] cannot find symbol
      symbol:   class DispatcherType
      location: class org.waarp.share.config.WebConfigurer
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/src/main/java/org/waarp/share/config/WebConfigurer.java:[148,32] cannot find symbol
      symbol:   class ServletContext
      location: class org.waarp.share.config.WebConfigurer
    [ERROR] /home/frederic/eclipse/vaadin/workspace/WaarpTest/target/generated-sources/openapi/src/main/java/org/waarp/share/web/api/ApiUtil.java:[5,26] package javax.servlet.http does not exist
    [INFO] 19 errors 
    [INFO] -------------------------------------------------------------
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------

Adding the following to the pom.xml fix this issue:

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
		</dependency>

Then I've got the second error, the one I've got too in my full project, which I do not know how to fix it.

    :: JHipster 🤓  :: Running Spring Boot 2.2.4.RELEASE ::
    :: https://www.jhipster.tech ::

    2020-02-11 17:13:55.398  INFO 10210 --- [           main] org.waarp.share.WaarpTestApp             : Starting WaarpTestApp on frederic-X510UQ with PID 10210 (/home/frederic/eclipse/vaadin/workspace/WaarpTest/target/classes started by frederic in /home/frederic/eclipse/vaadin/workspace/WaarpTest)
    2020-02-11 17:13:55.400 DEBUG 10210 --- [           main] org.waarp.share.WaarpTestApp             : Running with Spring Boot v2.2.4.RELEASE, Spring v5.2.3.RELEASE
    2020-02-11 17:13:55.401  INFO 10210 --- [           main] org.waarp.share.WaarpTestApp             : The following profiles are active: dev,swagger
    2020-02-11 17:13:56.920  WARN 10210 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
    2020-02-11 17:13:56.939 ERROR 10210 --- [           main] o.s.boot.SpringApplication               : Application run failed

    org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
    	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
    	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
    	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
    	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
    	at org.waarp.share.WaarpTestApp.main(WaarpTestApp.java:63)
    Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
    	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:203)
    	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179)
    	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153)
    	... 6 common frames omitted

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------

##### **Motivation for or Use Case**

Of course, before 6.7.0, there were not such errors (compile or runtime).
So this seems a regression from 6.6.0 to 6.7.0.

First issue is simple (add a missing dependency), but the second one is complex (at least for me, and Google didn't help me so much).

##### **Reproduce the error**

Simply: once installed version 6.7.0 of generator-jhipster

      jhispter

Answear default values to all

Once created, launch

      ./mvnw  -Pwebpack

First issue arrized. Add the following dependency ti the generated `pom.xml`

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
		</dependency>

Launch again

      ./mvnw  -Pwebpack

Second issues arrized.

##### **Suggest a Fix**

For the first one, add the default missing dependency.

For the second one, I do not know.

##### **JHipster Version(s)**

6.7.0 and regression with 6.6.0

##### **JHipster configuration**

INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**
```
waarp-test@0.0.1-SNAPSHOT /home/frederic/eclipse/vaadin/workspace/WaarpTest
└── generator-jhipster@6.7.0 
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.waarp.share",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.7.0",
    "applicationType": "monolith",
    "baseName": "WaarpTest",
    "packageName": "org.waarp.share",
    "packageFolder": "org/waarp/share",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1581437175988,
    "testFrameworks": ["gatling", "cucumber", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<summary>JDL entity definitions</summary>
<pre>
</pre>
</details>

##### **Environment and Tools**
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
git version 2.20.1
node: v13.8.0
npm: 6.13.7
yeoman: 3.1.1
Docker version 19.03.3, build a872fc2f86
docker-compose version 1.21.0, build unknown
INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

Ubuntu 19.4

-   [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
@fredericBregier,  instead of `./mvnw  -Pwebpack `, can you try `./mvnw` ?

**Comment by fredericBregier** [comment]
@vishal423 Indeed `./mvwn` did the trick on the test project...

Even the missing dependency is no more an issue. I was probably using an "old" documentation that specifies `-Pwebpack` to use...

I will return to my original project and see if it goes ok then.

**Comment by fredericBregier** [comment]
@vishal423 I confirm that `./mvwn` fully did the trick.

My bad, probably reading old doc...
Closing this issue then ;-)

Thank you!!
