### PR TITLE
Fix imports for micro frontends with Angular

### LINKED ISSUE #25550: Micro Frontends with Angular doesn't compile
##### **Overview of the issue**

Creating a microservices architecture with Angular results in a compilation error. 

```
> Task :webapp

> blog@0.0.1-SNAPSHOT webapp:build
> npm run clean-www && npm run webapp:build:dev


> blog@0.0.1-SNAPSHOT clean-www
> rimraf build/resources/main/static/


> blog@0.0.1-SNAPSHOT webapp:build:dev
> ng build --configuration development

- Generating browser application bundles (phase: setup)...
✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.

./src/main/webapp/app/entities/blog/blog/update/blog-update.component.ts:6:0-74 - Error: Module not found: Error: Can't resolve 'app/entities/blog/user/service/user.service' in '/Users/mraible/Downloads/micro-angular/blog/src/main/webapp/app/entities/blog/blog/update'

Error: src/main/webapp/app/entities/blog/blog/update/blog-update.component.ts:10:23 - error TS2307: Cannot find module 'app/entities/blog/user/user.model' or its corresponding type declarations.

10 import { IUser } from 'app/entities/blog/user/user.model';
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/main/webapp/app/entities/blog/blog/update/blog-update.component.ts:11:29 - error TS2307: Cannot find module 'app/entities/blog/user/service/user.service' or its corresponding type declarations.

11 import { UserService } from 'app/entities/blog/user/service/user.service';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/main/webapp/app/entities/blog/blog/update/blog-update.component.ts:36:66 - error TS2571: Object is of type 'unknown'.

36   compareUser = (o1: IUser | null, o2: IUser | null): boolean => this.userService.compareUser(o1, o2);
                                                                    ~~~~~~~~~~~~~~~~


Error: src/main/webapp/app/entities/blog/blog/update/blog-update.component.ts:86:34 - error TS2571: Object is of type 'unknown'.

86     this.usersSharedCollection = this.userService.addUserToCollectionIfMissing<IUser>(this.usersSharedCollection, blog.user);
                                    ~~~~~~~~~~~~~~~~


Error: src/main/webapp/app/entities/blog/blog/update/blog-update.component.ts:90:5 - error TS2571: Object is of type 'unknown'.

90     this.userService
       ~~~~~~~~~~~~~~~~


Error: src/main/webapp/app/entities/blog/blog/update/blog-update.component.ts:93:37 - error TS2571: Object is of type 'unknown'.

93       .pipe(map((users: IUser[]) => this.userService.addUserToCollectionIfMissing<IUser>(users, this.blog?.user)))
                                       ~~~~~~~~~~~~~~~~



npm ERR! Lifecycle script `webapp:build:dev` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: blog@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/micro-angular/blog
npm ERR! Lifecycle script `webapp:build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: blog@0.0.1-SNAPSHOT
npm ERR!   at location: /Users/mraible/Downloads/micro-angular/blog

> Task :webapp FAILED
```

##### **Motivation for or Use Case**

This worked in 8.1.0.

##### **Reproduce the error**

```
jhipster jdl reactive-mf.jdl --monorepository --workspaces --client-framework angular
cd blog
./gradlew
````

##### **JHipster Version(s)**

`main` branch

### PR DESCRIPTION
**Pull request by mraible**
Fixes #25550.

### CODE REVIEW

**Comment by mraible** [comment]
After this change, the following command succeeds and all apps can be compiled.

```
 jhipster jdl reactive-mf.jdl --monorepository --workspaces --client-framework angular
```

However, when I run `npm run e2e -ws` from the top level, tests in the blog project fail because they're trying to test the `Authority` entity, which does not exist.

Screenshot 2024-03-19 at 11 13 13 AM

**Comment by DanielFran** [comment]
Superseded by https://github.com/jhipster/generator-jhipster/pull/25552
