### ISSUE TITLE
response.json is not a function

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#7085]
##### **Overview of the issue**

After an upgrade from 4.13.3 to 4.14.0 the error message in the registration page do not work.
The problem is there is no json() function in the HttpErrorResponse. En arror is logged:

    core.js?593e:1440 ERROR TypeError: response.json is not a function
      at RegisterComponent.processError (register.component.ts?fe07:64)
      at SafeSubscriber.eval [as _error] (register.component.ts?fe07:52)
      ....

Changing the code in register.component.ts from:

    private processError(response) {
        this.success = null;
        console.log(response.error);
        if (response.status === 400 && response.json().type === LOGIN_ALREADY_USED_TYPE) {
            this.errorUserExists = 'ERROR';
        } else if (response.status === 400 && response.json().type === EMAIL_ALREADY_USED_TYPE) {
            this.errorEmailExists = 'ERROR';
        } else {
            this.error = 'ERROR';
        }
    }

to:

     import { HttpErrorResponse } from '@angular/common/http';
     ....
    private processError(response: HttpErrorResponse) {
        this.success = null;
        console.log(response.error.type);
        if (response.status === 400 && response.error.type === LOGIN_ALREADY_USED_TYPE) {
            this.errorUserExists = 'ERROR';
        } else if (response.status === 400 && response.error.type === EMAIL_ALREADY_USED_TYPE) {
            this.errorEmailExists = 'ERROR';
        } else {
            this.error = 'ERROR';
        }
    }

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by tibistibi** [comment]
to make sure it is not because of the upgrade I installed a fresh jhipster with the command 'jhipster' and left all options default:

the same code with the same problem

    private processError(response) {
        this.success = null;
        if (response.status === 400 && response.json().type === LOGIN_ALREADY_USED_TYPE) {
            this.errorUserExists = 'ERROR';
        } else if (response.status === 400 && response.json().type === EMAIL_ALREADY_USED_TYPE) {
            this.errorEmailExists = 'ERROR';
        } else {
            this.error = 'ERROR';
        }
    }

**Comment by jdubois** [comment]
I'm doing the fix, thanks @tibistibi !

**Comment by tibistibi** [comment]
code changes looks good! thanks for the fast response!

**Comment by jdubois** [comment]
Thanks, you did all the work - next time have a look at doing a pull request, so you keep the ownership of your code

**Comment by tibistibi** [comment]
yes that will be the next thing i now have a clue where the template's are for generating the components.

**Comment by jdubois** [comment]
Argh this makes our Protractor tests fail! It's quite incredible that fixing this makes the tests fail :-(

**Comment by tibistibi** [comment]
and the other way aground that not fixing it will make them succeed or differently said why didn't the test fail?

**Comment by jdubois** [comment]
Sorry, it's Karma, not Protractor!
I'm fixing this, in fact the test is false -> I guess the API changed at some point, because we did the code and the test to validate it, so this was quite secured.
I'm fixing this.

**Comment by tibistibi** [comment]
gogogo 👍

**Comment by malikfaizanhaider** [comment]
Same issue with response.json() that is deprecated in Angular6. Any soloution? 
`getRecipes() {
    this.httpClient.get('https://ng-recipe-10b53.firebaseio.com/recipes.json')
      .subscribe(
        (response: Response) => {
          const recipes: Recipe[]  = response.json();
          this.recipeService.setRecipes(recipes);
        }
      );
  }`
