### ISSUE TITLE
Sorting is not working in 3.0

### ISSUE THREAD

**Issue by erkieh** [jhipster/generator-jhipster#3181]
From current master 3e9436ef9d7b60b9edec9ec7dedee582a49f0d8c I recieve "Uncaught TypeError: $scope.callback is not a function" when I try to sort an entity table. 

I tried replacing the $scope.callback() with vm.callback() in the sort.directive.js, that gets the sorting to work, but the icon does not change. triggerApply recieves an array of undefined elements.

**Comment by deepu105** [comment]
@geraldhumphries this seems related your recent change can you plz take a look

**Comment by geraldhumphries** [comment]
Okay, looking into it.
