### ISSUE TITLE
Issue with jhipster cli version 4.5.0 

### ISSUE THREAD

**Issue by ecukalla** [jhipster/generator-jhipster#5797]
##### **Overview of the issue**
After the upgrade to 4.5.0 and using jhipster (cli) I ge the following error:

    ➜  ~ yarn global upgrade generator-jhipster
    yarn global v0.24.5
    warning package.json: No license field
    warning No license field
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 📃  Rebuilding all packages...
    success Saved lockfile.
    success Saved 9 new dependencies.
    ├─ commander@2.9.0
    ├─ didyoumean@1.2.1
    ├─ generator-jhipster@4.5.0
    ├─ graceful-readlink@1.0.1
    ├─ jhipster-core@1.3.2
    ├─ lodash.difference@4.5.0
    ├─ lodash.uniq@4.5.0
    ├─ tabtab@2.2.2
    └─ yeoman-environment@1.6.6
    warning No license field
    ✨  Done in 8.04s.
    ➜  ~ yarn --version
    0.24.5
    ➜  ~ node --version
    v7.10.0
    ➜  ~ npm --version
    4.6.1
    ➜  ~ mkdir testapp
    ➜  ~ cd testapp 
    ➜  testapp jhipster
    module.js:472
        throw err;
        ^
    
    Error: Cannot find module 'chalk'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/edmond/Documents/dev/java/generator-jhipster/cli/jhipster.js:21:15)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
    ➜  testapp

But when running it with Yeoman it works.
    ➜  testapp yo jhipster
    
            ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
            ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
            ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
      ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
      ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
       ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
    
                                https://jhipster.github.io
    
    Welcome to the JHipster Generator v4.5.0
    Documentation for creating an application: https://jhipster.github.io/creating-an-app/
    Application files will be generated in folder: /Users/edmond/testapp
    ? (1/16) Which *type* of application would you like to create? (Use arrow keys)
    ❯ Monolithic application (recommended for simple projects) 
      Microservice application 
      Microservice gateway 
      [BETA] JHipster UAA server (for microservice OAuth2 authentication) 

I'm on a OSX 10.12.5.

**Comment by ecukalla** [comment]
I think I've wrongly reported it :|.

When checking the link to jhipster cli I get this:
    
    ➜  ~ ls -l `which jhipster`
    lrwxr-xr-x  1 edmond  staff  59 May 20 00:50 /Users/edmond/.npm-packages/bin/jhipster -> ../../Documents/dev/java/    generator-jhipster/cli/jhipster.js
    ➜  ~ cd Documents/dev/java/generator-jhipster 
    ➜  generator-jhipster git:(master) yarn unlink
    yarn unlink v0.24.5
    success Unregistered "generator-jhipster".
    ✨  Done in 0.10s.
    ➜  generator-jhipster git:(master)

... was testing yesterday the current master branch & I'd linked to it. Now that I did the yarn unlink I can't get jhispter cli.
I also did yarn global remove & yarn global add generator-jhipster and still dont get a jhipster cli (jhipster).

Can you please advice how to fix it.
Thanks.

**Comment by gmarziou** [comment]
It seems there are also issues with jhipster cli on Windows: https://stackoverflow.com/questions/44083065/jhipster-is-not-recognized-as-an-internal-or-external-command-operable-program

**Comment by ecukalla** [comment]
The jhipster cli is having the issue, while on osx i can still run yo jhipster with success:
    ➜  ~ mkdir yoworks
    ➜  ~ cd yoworks 
    ➜  yoworks yo jhipster
    
            ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
            ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
            ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
      ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
      ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
       ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
    
                                https://jhipster.github.io
    
    Welcome to the JHipster Generator v4.5.0
    Documentation for creating an application: https://jhipster.github.io/creating-an-app/
    Application files will be generated in folder: /Users/edmond/yoworks
    ? (1/16) Which *type* of application would you like to create? (Use arrow keys)
    ❯ Monolithic application (recommended for simple projects) 
      Microservice application 
      Microservice gateway 
      [BETA] JHipster UAA server (for microservice OAuth2 authentication)

**Comment by mystdeim** [comment]
Confirmed issue on ubuntu 16.04.
``` 
-> npm install -g generator-jhipster
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "generator-jhipster"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path /home/romanovi/.npm-global/lib/node_modules/generator-jhipster/cli/jhipster.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/romanovi/.npm-global/lib/node_modules/generator-jhipster/cli/jhipster.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/romanovi/.npm-global/lib/node_modules/generator-jhipster/cli/jhipster.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

```

Version 4.4.1 works good

**Comment by jdubois** [comment]
Many thanks @ecukalla @mystdeim -> if anybody has any more issue, please add them here!!

- First of all, we are very sorry about it: it works perfectly fine in "dev mode" (using our [development setup here](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#setup)). So it's one of those cases where NPM/Yarn do not work the same in dev and in a package...
- It looks like @pascalgrimaud found a solution, see the [dev mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jhipster-dev/R9FMH5Vr-LU/_0vy-QGJCQAJ)
- It seems different depending on the OS, and if you use NPM/Yarn, so that does a lot of combinations.
- What is just **crazy** is that our [Docker build](https://hub.docker.com/r/jhipster/jhipster/) works, so there's an installation trick somewhere, but we didn't do it on purpose
- Of course v4.1.1 still works - if we don't find an easy solution over the week-end, we'll revert to the older version

**Comment by mystdeim** [comment]
My extra points: I refused to use yarn because there's some weird issues on ubuntu while simultaneously using npm and yarn. Just `npm install generator-jhipster@4.4.1` and it works )

**Comment by pascalgrimaud** [comment]
I find time to made some more tests.

@jdubois :
- on your local, test `npm pack`: it will create a new file `generator-jhipster-4.5.0.tgz`. This tgz is probably what is upload to NPM repo and doesn't contain the `cli` folder
- now, if you modify the `package.json` for including `cli` folder then test `npm pack` again. This `generator-jhipster-4.5.0.tgz` contains what we want. I will do a PR for that!

**Comment by pascalgrimaud** [comment]
About the **Docker build**, what it is done:
- add source from repo: https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile#L50
- then install from this source: https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile#L63
- so the folder contains the `cli` folder
- so it's similar in dev, as Docker doesn't use the release from NPM repo, but the repo from GitHub

It is done to have for the same Dockerfile:
- a Docker image 'master' which is always up-to-date with master
- a Docker image for every release/tag

**Comment by pascalgrimaud** [comment]
@mystdeim : understood about refusing to use Yarn. That's why we still support both: NPM and Yarn.
Did you see this tweet about NPM5? https://twitter.com/maybekatz/status/865393382260056064 :-)

**Comment by jdubois** [comment]
Thanks a lot @pascalgrimaud !!! This looks like you solve the issue, so I'm closing this - I'll do some quick tests, and a release

**Comment by miy4mori** [comment]
not found cli too.
```
C:\Dev\repo\jhipster\monolith
# node -v
v6.10.3

C:\Dev\repo\jhipster\monolith
# yarn -v
yarn install v0.24.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
Done in 0.08s.

C:\Dev\repo\jhipster\monolith
# yarn global ls
yarn global v0.24.5
warning No license field
info "generator-jhipster@4.5.0" has binaries:
   - jhipster
info "yo@1.8.5" has binaries:
   - yo
   - yo-complete
Done in 2.53s.

C:\Dev\repo\jhipster\monolith
# which jhipster
which: no jhipster in (/c/Dev/cmder/bin:/cmd:/c/Dev/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/c/Dev/cmder/vendor/conemu-maximus5:/c/Dev/cmder/vendor/conemu-maximus5/ConEmu:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/HashiCorp/Vagrant/bin:/c/Program Files/nodejs:/c/Dev/jdk/jdk-8u121-windows-x64/bin:/c/Dev/maven/apache-maven-3.3.9/bin:/c/Dev/gradle/gradle-3.5/bin:/c/Dev/php/php7/php-7.1.5-nts:/c/Dev/php/phar/composer:/c/Dev/php/phar/phpunit:/c/Dev/redis/Redis-x64-3.2.100:/c/Dev/mysql/mysql-5.7.18-winx64/bin:/c/Program Files (x86)/Yarn/bin:/c/Users/miy4mori/AppData/Local/Microsoft/WindowsApps:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Microsoft VS Code/bin:/c/Users/miy4mori/AppData/Roaming/npm:/c/Users/miy4mori/AppData/Local/Yarn/bin:/usr/bin:/usr/share/vim/vim74:/c/Dev/cmder)

C:\Dev\repo\jhipster\monolith
#
```

**Comment by jdubois** [comment]
Thanks @miy4mori
Unfortunately I think the only way to test the fix is to do a release, so I'm doing one ASAP

**Comment by jdubois** [comment]
And @miy4mori as you are on Windows, can you test the new release when it's ready, and tell us if everything is fine?

**Comment by deepu105** [comment]
Thanks a lot guys. Sorry I wasn't available to help

**Comment by jdubois** [comment]
The release is done!
Crossing fingers :-)

**Comment by ecukalla** [comment]
Happy Jhipster 4.5.1 @ all from OSX

    ➜  testapp jhipster
    Running default command
    Executing jhipster:app
    
            ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
            ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
            ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
      ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
      ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
       ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
    
                                https://jhipster.github.io
    
    Welcome to the JHipster Generator v4.5.1
    Documentation for creating an application: https://jhipster.github.io/creating-an-app/
    Application files will be generated in folder: /Users/edmond/testapp
    ^C
    
    ➜  testapp jhipster --help 
    
      Usage: jhipster [command] [options]
    
    
      Commands:
    
        app                       Create a new JHipster application based on the selected options
        aws                       Deploy the current application to Amazon Web Services
        ci-cd                     Create pipeline scripts for popular Continuous Integration/Continuous Deployment tools
        client                    Create a new JHipster client-side application based on the selected options
        cloudfoundry              Generate a `deploy/cloudfoundry` folder with a specific manifest.yml to deploy to Cloud     Foundry
        docker-compose            Create all required Docker deployment configuration for the selected applications
        entity [name]             Create a new JHipster entity: JPA entity, Spring server-side components and Angular     client-side components
        export-jdl [jdlFile]      Create a JDL file from the existing entities
        heroku                    Deploy the current application to Heroku
        import-jdl [jdlFiles...]  Create entities from the JDL file passed in argument
        info                      Display information about your current project and system
        kubernetes                Deploy the current application to Kubernetes
        languages [languages...]  Select languages from a list of available languages. The i18n files will be copied to the /    webapp/i18n folder
        openshift                 Deploy the current application to OpenShift
        rancher-compose           Deploy the current application to Rancher
        server                    Create a new JHipster server-side application
        service [name]            Create a new Spring service bean
        upgrade                   Upgrade the JHipster version, and upgrade the generated application
        completion                Print command completion script
    
      Options:
    
        -h, --help     output usage information
        -d, --debug    enable debugger
        -V, --version  output the version number
    
      For more info visit https://jhipster.github.io
    
    ➜  testapp

**Comment by pascalgrimaud** [comment]
Don't be sorry @deepu105 and no worry!
Enjoy your weekend in :es: !

**Comment by jdubois** [comment]
Everything looks OK, thank you so much everyone!!!!!

**Comment by miy4mori** [comment]
@jdubois Sorry,I did not notice the notification. the new release worked very well on Windows.
But I can't import jdl without client files,I try to run `jhipster server import-jdl my_file.jdl` or `jhipster --skip-client import-jdl my_file.jdl` and it still generate client files.Does anyone have any ideas how can I import jdl without client files?

**Comment by jdubois** [comment]
@miy4mori not sure about this (I never skip the client!), but I think this comes from your initial config: if it's stored in your `.yo-rc.json`, then it can't be overriden (unless you modify this file, of course!)

**Comment by deepu105** [comment]
You cannot unless you already generate the app with skip-client. I need to
check further to see if we can make this a supported option


Thanks & Regards,
Deepu

**Comment by miy4mori** [comment]
@jdubois @deepu105 
I already generate the app with `skip-client`  or `server`,But it still generate client files,Here is my jdl and console output.I hope this is helpful to you. Thanks for attention
jhipster-jdl.jh
```
entity Post {
	title String
}
```
console output.
```
C:\Dev\repo\jhipster\demo
# jhipster server demo
Executing jhipster:server
? (1/16) What is the base name of your application? demo
? (2/16) What is your default Java package name? com.miy4mori.demo
? (3/16) Do you want to use the JHipster Registry to configure, monitor and scale your application? No
? (4/16) Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? (5/16) Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? (6/16) Which *production* database would you like to use? MySQL
? (7/16) Which *development* database would you like to use? MySQL
? (8/16) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? (9/16) Would you like to use Maven or Gradle for building the backend? Gradle
? (10/16) Which other technologies would you like to use? (Press <space> to select, <a> to toggle all, <i> to inverse selection)
? (11/16) Would you like to enable internationalization support? No
   create ......
Server application generated successfully.

Run your Spring Boot application:
 ./gradlew (gradlew if using Windows Command Prompt)
Execution complete

C:\Dev\repo\jhipster\demo
# jhipster info
Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

C:\Dev\repo\jhipster\demo
`-- (empty)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.miy4mori.demo"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "demo",
    "packageName": "com.miy4mori.demo",
    "packageFolder": "com/miy4mori/demo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "1c3cdfe21ff9bc8347676a2d570a6ea5b5933a59",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.0.windows.1

node: v6.10.3

npm: 4.6.1

yeoman: 1.8.5

yarn: 0.24.5

Execution complete

C:\Dev\repo\jhipster\demo
# jhipster import-jdl jhipster-jdl.jh
Executing jhipster:import-jdl jhipster-jdl.jh
The jdl is being parsed.
Writing entity JSON files.
Generating entities.

Found the .jhipster/Post.json configuration file, entity can be automatically generated!


The entity Post is being updated.


Unable to find src/main/webapp/app/layouts/navbar/navbar.html or missing required jhipster-needle. Reference to post not added to menu.

   create src\main\resources\config\liquibase\changelog\20170529152115_added_entity_Post.xml
   create src\main\java\com\miy4mori\demo\domain\Post.java
   create src\main\java\com\miy4mori\demo\repository\PostRepository.java
   create src\main\java\com\miy4mori\demo\web\rest\PostResource.java
   create src\test\java\com\miy4mori\demo\web\rest\PostResourceIntTest.java
   create src\test\gatling\simulations\PostGatlingTest.scala
 conflict src\main\resources\config\liquibase\master.xml
? Overwrite src\main\resources\config\liquibase\master.xml? overwrite this and all others
    force src\main\resources\config\liquibase\master.xml
    force src\main\java\com\miy4mori\demo\config\CacheConfiguration.java
   create src\main\webapp\app\entities\post\posts.html
   create src\main\webapp\app\entities\post\post-detail.html
   create src\main\webapp\app\entities\post\post-dialog.html
   create src\main\webapp\app\entities\post\post-delete-dialog.html
   create src\main\webapp\app\entities\post\post.state.js
   create src\main\webapp\app\entities\post\post.controller.js
   create src\main\webapp\app\entities\post\post-dialog.controller.js
   create src\main\webapp\app\entities\post\post-delete-dialog.controller.js
   create src\main\webapp\app\entities\post\post-detail.controller.js
   create src\main\webapp\app\entities\post\post.service.js
   create src\test\javascript\spec\app\entities\post\post-detail.controller.spec.js

Running gulp Inject to add javascript to index
```

**Comment by miy4mori** [comment]
@jdubois @deepu105
I think the problem is `.yo-rc.json`.

generator-jhipster/generators/import-jdl/index.js line 52
```
   this.skipClient = this.config.get('skipClient');
```
But `jhipster server` not add `skipClient` into `.yo-rc.json`,When I add this item, it worked and not generate client files.
