### ISSUE TITLE
JHipster 8.2.0 release

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#25259]
##### **Overview of the feature request**

A new release with:
- rewritten upgrade generator.
- improved sonar statistics with increased coverage and less code smells.
- lots of old bug reports fixed.
- latest spring-boot/angular/react/vue.
- continue angular's new reactivity model migration.
- lots of internal work.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by wangxinxx** [comment]
Will a new version be released soon?

**Comment by deepu105** [comment]
If there are no blockers I can make a release today/tomorrow

**Comment by mshima** [comment]
No blocker.

**Comment by deepu105** [comment]
Cool I'll start the release

**Comment by mraible** [comment]
I just tried generating my 21-Points Health app using the `jhipster` command. It works, but it seems like the questions are in a different order. Maybe this is as designed because the test prompt now applies to the backend and frontend separately?

JHipster 7:

<img width="1442" alt="generating-21points" src="https://github.com/jhipster/generator-jhipster/assets/17892/077f280f-fe71-478e-a6bd-6f1fbcfb254c">

JHipster main branch:

<img width="1442" alt="Screenshot 2024-03-18 at 9 52 50 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/a97f0b08-e3b0-4044-a076-856578b6ff90">

Also, it'd be nice to get rid of this warning since it happens in a brand new app and I feel there shouldn't be warnings in a brand new app.

```
WARNING! Ignoring 'UserManagement' definitions as it is using a built-in Entity 'Authority': 
'otherEntityRelationshipName' is set with value 'undefined' at relationship 'authority' but no back-reference was found
```

**Comment by mraible** [comment]
I just found a compilation issue when using Neo4j. Steps to reproduce:

Generate a microservices and microfrontend architecture using the following command:

```
jhipster jdl reactive-mf.jdl --monorepository --workspaces
```

Try to compile the resulting `blog` project and you'll get an error:

```
/Users/mraible/Downloads/micro-frontends/blog/src/main/java/com/okta/developer/blog/web/rest/TagResource.java:183: error: cannot find symbol
            .zipWith(tagRepository.findAllBy(pageable).collectList())
                                  ^
  symbol:   method findAllBy(Pageable)
  location: variable tagRepository of type TagRepository
/Users/mraible/Downloads/micro-frontends/blog/src/main/java/com/okta/developer/blog/web/rest/PostResource.java:191: error: cannot find symbol
            .zipWith(postRepository.findAllBy(pageable).collectList())
                                   ^
  symbol:   method findAllBy(Pageable)
  location: variable postRepository of type PostRepository
2 errors
3 warnings

> Task :compileJava FAILED
```

This is a regression that worked with JHipster 8.1.0.

**Comment by mraible** [comment]
Here's another issue that's quite strange when running `jhipster jdl reactive-mf.jdl --monorepository --workspaces`. If I hit Ctrl+C right after the "Thanks for using JHipster!" message, it only takes around 2 minutes.

<img width="1442" alt="Screenshot 2024-03-18 at 11 41 24 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/0293b526-ba32-46a5-ab53-94b7c3636d11">

However, if I wait for the generation process to complete, it takes 10 minutes! 😳

<img width="1442" alt="Screenshot 2024-03-18 at 11 53 01 AM" src="https://github.com/jhipster/generator-jhipster/assets/17892/ddd9766d-d0f0-4ed5-939e-a801461e90cc">

I'm on an Apple M3 Max with Sanoma 14.3.1 (23D60).

**Comment by mraible** [comment]
I found another issue with my micro frontends demo. There is a warning that happens when building the gateway. 

```
WARNING in ../node_modules/@module-federation/utilities/dist/index.cjs.js 862:122-132
Critical dependency: the request of a dependency is an expression
```

This is kinda awkward because it does pop up an alert when building. Everything still seems to work though. It gets more intrusive when you run `npm start` because the warning has to be dismissed.

<img width="1112" alt="Screenshot 2024-03-18 at 12 58 36 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/2e59ad85-ff92-465b-9093-66aef6c2a36e">

**Comment by mshima** [comment]
> However, if I wait for the generation process to complete, it takes 10 minutes! 😳

Looks related to kubernetes generator.
If you remove kubernetes it is quick.

**Comment by mraible** [comment]
@mshima I tried `@module-federation@utilities` v3.0.6 and the issue still happens.

**Comment by deepu105** [comment]
ok seems like there are some issues, so i'm not starting the release

**Comment by deepu105** [comment]
Even with kubernetes it shouldnt take 10 minutes, so thgere might be some regressions

**Comment by mshima** [comment]
@deepu105 it's not a regression, happens on v8.1.0 on Node 20.
```
npx generator-jhipster@8.1.0 jdl reactive-mf.jdl --ignore-deployments --json-only
```

Node 18 works as expected.
I don't think we should delay v8.1.0 due to this issue.

**Comment by mshima** [comment]
The issue is related to download sample command.
```
jhipster download reactive-mf.jdl
```

**Comment by mshima** [comment]
Hang is fixed in https://github.com/jhipster/generator-jhipster/pull/25543.

**Comment by deepu105** [comment]
@mraible I'll wait for your go ahead for the release. Let me know if there is anything else you find

**Comment by mshima** [comment]
@mraible we are having this issue https://github.com/jhipster/generator-jhipster/issues/24134.
Now that devserver check is fixed it will break if it’s not fixed by upstream.

**Comment by mraible** [comment]
@deepu105 All the issues I found are now fixed. Please proceed with the release. 

💡 If Gradle 8.7 is released (with Java 22 support), that might be useful for marketing.

**Comment by deepu105** [comment]
Do we support Java 22, I dont see it in the supported list

**Comment by mraible** [comment]
Java 22 doesn't work with the latest version of Gradle (v8.6) and Java 22 won't be supported by Gradle until Gradle 8.7. We could use RC3 if we wanted. 

https://twitter.com/gradle/status/1767496178877272204

I just tried using the main branch and `jhipster --defaults` with Java 22 and `mvn verify` fails (after updating the `pom.xml` to allow Java 22). 

```
[ERROR] Failures:
[ERROR]   CRLFLogConverterTest.testToAnsiString:131
expected: "input"
 but was: "input"
[ERROR]   CRLFLogConverterTest.transformShouldReplaceNewlinesAndCarriageReturnsWithAnsiStringWhenMarkersDoNotContainCRLFSafeMarkerAndLoggerIsNotSafeAndAnsiElementIsNotNull:99 expected: <Test_input_string> but was: <Test_input_string>
[INFO]
[ERROR] Tests run: 38, Failures: 2, Errors: 0, Skipped: 0
```

`mvn verify` works if I use Java 21. 

For these reasons, I'd say we don't support 22 yet. We can release 8.2.1 once we do.

**Comment by mraible** [comment]
@deepu105 First of all, thanks for doing the release. Unfortunately, it seems to be broken when I try to reproduce the issue in https://github.com/jhipster/generator-jhipster/issues/25255. 

`jhipster jdl app.jdl` results in the following error:

```
Welcome to JHipster v8.2.0

INFO! Generating jdls app.jdl
     info Generating 1 application
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/

  Application files will be generated in folder: /Users/mraible/Downloads/websocket
 _______________________________________________________________________________________________________________

ERROR! An error occured while running jhipster:server#writeFiles
ERROR! ERROR! /Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs:424
    422| <%_ } _%>
    423|         secondUser.setLangKey(firstUser.getLangKey());
 >> 424| <%_ if (generateSpringAuditor) { _%>
    425|         secondUser.setCreatedBy(firstUser.getCreatedBy());
    426|         secondUser.setCreatedDate(firstUser.getCreatedDate());
    427|         secondUser.setLastModifiedBy(firstUser.getLastModifiedBy());

generateSpringAuditor is not defined
ReferenceError: /Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs:424
    422| <%_ } _%>
    423|         secondUser.setLangKey(firstUser.getLangKey());
 >> 424| <%_ if (generateSpringAuditor) { _%>
    425|         secondUser.setCreatedBy(firstUser.getCreatedBy());
    426|         secondUser.setCreatedDate(firstUser.getCreatedDate());
    427|         secondUser.setLastModifiedBy(firstUser.getLastModifiedBy());

generateSpringAuditor is not defined
    at JHipsterServerGenerator.eval ("/Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs":418:8)
    at AccountResourceIT.java (/Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:703:17)
    at /Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:260:40
    at new Promise (<anonymous>)
    at tryHandleCache (/Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:258:14)
    at exports.renderFile (/Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:491:10)
    at renderFile (file:///Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/dist/util.js:65:16)
    at MemFsEditor.processFile (file:///Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/dist/actions/copy-tpl-async.js:13:20)
    at MemFsEditor.applyProcessingFileFunc (file:///Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/dist/actions/copy-async.js:10:54)
    at MemFsEditor._copySingleAsync (file:///Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/dist/actions/copy-async.js:76:52) {
  path: '/Users/mraible/.nvm/versions/node/v20.11.1/lib/node_modules/generator-jhipster/dist/generators/server/templates/src/test/java/_package_/web/rest/AccountResourceIT.java.ejs'
}
```

**Comment by deepu105** [comment]
ya just noticed this. I don't know how this got past the CI. Did something change after your last tests

**Comment by mraible** [comment]
I'm not sure what the issue is. If I clone the repo and run `npm i && npm link`, everything works as expected. 

Any ideas, @mshima?

**Comment by mraible** [comment]
@deepu105 The only thing I can think of is the deployed artifact doesn't contain some files. Did you run `npm run build` before publishing? If not, we should add the following to our scripts so it always happens.

```json
"prepublishOnly": "npm run build",
```

**Comment by Super-Orion** [comment]
<img width="1619" alt="微信图片_20240320234844" src="https://github.com/jhipster/generator-jhipster/assets/51911810/86a7ee51-b116-4fbc-8809-76215bc6b6d4">
I'm also having this issue when building a gateway project with the new version, but I didn't select websocket

**Comment by mshima** [comment]
> I'm not sure what the issue is. If I clone the repo and run `npm i && npm link`, everything works as expected.
> 
> Any ideas, @mshima?

The published package has old `mjs` files.
Added prebuild script here https://github.com/jhipster/generator-jhipster/pull/25563.

**Comment by deepu105** [comment]
But running `npm publish` runs prepare which runs the build. I can see the build logs in my terminal from the ansible job

**Comment by deepu105** [comment]
So clean was missing

**Comment by deepu105** [comment]
@mraible its not possible to unpublish since there are dependent packages for this. I can only mark it deprecated and release 8.2.1

**Comment by deepu105** [comment]
8.2.1 is released

**Comment by deepu105** [comment]
@mshima Btw the "Generators / generate-blueprint / check-generator-generate-blueprint (push) " job is still failing with a permission error
