### ISSUE TITLE
Languages support is not working in release 2.20.0

### ISSUE THREAD

**Issue by saminurmi** [jhipster/generator-jhipster#1966]
I have tried three times to generate a new project with yo:jhipster and in every case language support is not working. JavaScript console is giving the error message like that:

TypeError: Language.getCurrent is not a function
    at app.js:19
    at Scope.$broadcast (angular.js:16238)
    at Object.transitionTo (angular-ui-router.js:3229)
    at Object.go (angular-ui-router.js:3068)
    at buildingSite.js:67
    at processQueue (angular.js:14634)
    at angular.js:14650
    at Scope.$eval (angular.js:15916)
    at Scope.$digest (angular.js:15727)
    at Scope.$apply (angular.js:16024)

![screen shot 2015-09-02 at 16 27 32](https://cloud.githubusercontent.com/assets/9211002/9632389/94e598a2-518f-11e5-8f4a-ec27f2439c8c.png)

**Comment by gmarziou** [comment]
It works for me, so I suspect you had an error during grunt build or bower install, or veen eralier in the browser console that you did not notice.

Anyway, please read [issue submission guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue) to improve your issue report.

**Comment by gmarziou** [comment]
Closing the issue until we get more data.

**Comment by saminurmi** [comment]
hi! 

I recognised that running jhipster-uml ac.xmi -paginate breaks the language selection. I have no idea why. I generated pure jhipster project with languages support and yes, it is working. Before I have always generated entities as well before testing and that is the reason why it has never worked before. I have an entity with name language as well, but it shouldn't effect like that?
Parser detected: MODELIO.

? Please choose the entities you want to paginate: 
? Please choose the pagination style: Pagination links
? Do you want to add an other pagination style? No
Creating:
	language
	timeLog
	Tiedonantaja
	foreignIdType
	empolymentRelationship
	Country
	Address
	Employer
	employee
	agency
	BuildingSite
	buildingSiteStatus

**Comment by gmarziou** [comment]
OK, so I think you'd get more help by opening an issue in [jhipster-uml project](https://github.com/jhipster/jhipster-uml/issues)

**Comment by saminurmi** [comment]
Hi!

The reason was it, that I had the language table/entity as well. I changed
it and everything is working fine. I think that somebody should tell thai
it is reserved word.

Cheers,
Sami

2015-09-03 23:34 GMT+03:00 Gaël Marziou <notifications@github.com>:

**Comment by gmarziou** [comment]
Could you clarify is it Thai or Language that should be a reserved word?

**Comment by deepu105** [comment]
I think its a typo and he meant language

**Comment by saminurmi** [comment]
Oh sorry :) It was a typo. I meant it like that:

"I think that somebody should tell that it is reserved word."
So the name of the table and entity is language and when I changed it to
something else, everything was working fine. Before that after generated
entities from UML class diagram (xmi-file) language drop down went always
broken. Sorry my English...

Cheers,
Sami

2015-09-04 17:30 GMT+03:00 Deepu k Sasidharan <notifications@github.com>:

> I think its a typo and he meant language

**Comment by gmarziou** [comment]
No problem we have already a list of reserved words that can't be used as an entity name, I will extend it.

**Comment by gmarziou** [comment]
Or we could create JHipster Angular modules and namespace to avoid such name conflicts.

**Comment by ddewaele** [comment]
@gmarziou : Just noticed we were having the same issue. (I assume after we introduced a Language entity). Is the reserved word check only applied in interactive mode ? (I just copied our .jhipster/*.json files over to a new jhipster 2.77 installation and it didn't complain about the Language entity when I recreated the entities.

**Comment by deepu105** [comment]
There is no more jhipster reserved words on the current master so this shouldn't be an issue on 3.0

**Comment by ddewaele** [comment]
@deepu105 : But I guess the namespace issue remains then ? (Introducing a Language Entity will cause a conflict betwen the entity service and the jHipster built-in AngularJS Language factory ?

**Comment by andidev** [comment]
@ddewaele @deepu105 
Good point, we have not thought of that. How should we solve this. I guess the only solution is to bring back the reserved words?

**Comment by deepu105** [comment]
@andidev or should we prepend the service names as well?

**Comment by andidev** [comment]
Maybe, not sure about this. Then they would be called LanguageManagerService while in fact it is some kind of repository service not only bound to the management of the entity. Feels a bit wrong.

**Comment by deepu105** [comment]
ya, you are right.
what about prepending it with `Jhi` so that it will become `JhiLanguage.service.js` ?

**Comment by deepu105** [comment]
I guess @jdubois is not a big fan of prepending `Jhi` to generated code :wink:

**Comment by ddewaele** [comment]
Perhaps platform or framework might be better. AFAIK there are no
namespaces in Angularjs so there aren't that many options besides
prepending.

**Comment by andidev** [comment]
@deepu105 
When you mean prepend with jhi do you mean the pretending the language service or the generated entity language service?

**Comment by deepu105** [comment]
prepend the language service and other service we provide in the default app

Thanks & Regards,
Deepu
