### ISSUE TITLE
Error: Cannot find module 'yeoman-generator'

### ISSUE THREAD

**Issue by jksoftpro** [jhipster/generator-jhipster#1559]
Hi guys, 

I am using the development master branch, working on Mac OSX 10.10. Any ideas why I would get this error:
Any help greatly appreciated.

$ yo jhipster
module.js:338
    throw err;
          ^
Error: Cannot find module 'yeoman-generator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/softpro/devel/git/generator-jhipster-gitlabfork/app/index.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by jdubois** [comment]
You had an error when installing, try `npm install`.
